# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"HFF_k_matrix": "00_core.ipynb",
         "sklearn_kt_regressor": "00_core.ipynb",
         "glmnet_kt_regressor": "00_core.ipynb",
         "RFchannel": "01_RFsimulation.ipynb"}

modules = ["core.py",
           "RFsimulation.py"]

doc_url = "https://elaird6.github.io/rfml_localization/"

git_url = "https://github.com/elaird6/rfml_localization/tree/master/"

def custom_doc_links(name): return None
